### ISSUE TITLE
fix use of death in calc_nqx

### ISSUE THREAD

**Issue by JoseAntonioOrtega** [mrc-ide/demogsurv#11]
Despite the existence of an argument `death`, it is not used within the function resulting in errors when forming the model.matrix.

To fix it you just need to include

data$death <- data[[death]]

In the first lines of the function.

**Comment by jeffeaton** [comment]
Thank you, oh dear!  I think I see what you mean, but it will take me a bit of stepping through the code to remind myself what everything is doing there.

Do you have a reproducible code example of this failing and giving an error that I can use to check it?

Thanks,
Jeff

**Comment by JoseAntonioOrtega** [comment]
This would do:

```
data(zzbr)
zzbr$d <- zzbr$b5 == "no"
zzbr$dod <- zzbr$b3 + zzbr$b7 + 0.5

calc_nqx(zzbr,death="d")
````

**Comment by JoseAntonioOrtega** [comment]
Message; 

`Error in model.frame.default(f, data = data, na.action = na.pass, death = death,  : 
  variable lengths differ (found for '(death)')`

**Comment by jeffeaton** [comment]
Thanks so much!!
